[tool.poetry]
name = "fin-platform"
version = "0.1.0"
description = ""
authors = ["KBI"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
openai = "^1.6.1"
langchain = "^0.0.354"
fastapi = "^0.108.0"
pydantic = "^2.5.3"
pydantic-settings = "^2.1.0"
sqlmodel = "^0.0.14"
mysql-connector = "^2.2.9"
tiktoken = "^0.5.2"
faiss-cpu = "^1.7.4"


[tool.poetry.group.dev.dependencies]
python-dotenv = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
