name: Deploy to AWS EC2

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-docker@v2

    - name: Build and push Docker images
      run: |
        docker-compose build
        docker-compose push

    - name: SSH into EC2 and pull changes
      uses: appleboy/ssh-action@v2
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          git pull origin main
          docker-compose down
          docker-compose up -d
