name: Deploy to AWS EC2

on:
  push:
    branches:
      - deployment
env:
  PYTHON_VERSION: "3.11"
  FIN_PLATFORM_DB_USER: "fin_platform"
  FIN_PLATFORM_DB_HOST: "0.0.0.0"
  FIN_PLATFORM_DB_PORT: "3306"
  FIN_PLATFORM_DB_PASS: "fin_platform"
  FIN_PLATFORM_DATABASE: "mybank"
  OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
  JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
  FRONTEND_URL: ${{vars.FRONTEND_URL}}

jobs:
  deploy:
    runs-on: self-hosted
    services:
      fin_platform-db:
        image: bitnami/mysql:8.0.30
        env:
          MYSQL_ROOT_PASSWORD: "fin_platform"
          MYSQL_ROOT_USER: "fin_platform"
          MYSQL_DATABASE: "mybank"
          MYSQL_AUTHENTICATION_PLUGIN: "mysql_native_password"
        options: >-
          --health-cmd="mysqladmin ping -u root"
          --health-interval=15s
          --health-timeout=5s
          --health-retries=6
        ports:
          - 3306:3306
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

#    - name: Build docker image
#      run: |
#        sudo docker-compose build
#
#    - name: SSH into EC2 and pull changes
#      uses: appleboy/ssh-action@v3
#      with:
#        host: ${{ secrets.EC2_HOST }}
#        username: ${{ secrets.EC2_USERNAME }}
#        key: ${{ secrets.EC2_PRIVATE_KEY }}
#        script: |
#          git pull origin main
#          docker-compose down
#          docker-compose up -d
