name: Backend Tests

on:
  push:
    branches:
      - test2

env:
  PYTHON_VERSION: "3.11"
  FIN_PLATFORM_DB_USER: "fin_platform"
  FIN_PLATFORM_DB_HOST: "0.0.0.0"
  FIN_PLATFORM_DB_PORT: "3306"
  FIN_PLATFORM_DB_PASS: "fin_platform"
  FIN_PLATFORM_DATABASE: "mybank"
  OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
  JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
  FRONTEND_URL: ${{vars.FRONTEND_URL}}

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fin_platform
    services:
      fin_platform-db:
        image: bitnami/mysql:8.0.30
        env:
          MYSQL_ROOT_PASSWORD: "fin_platform"
          MYSQL_ROOT_USER: "fin_platform"
          MYSQL_DATABASE: "fin_platform"
          MYSQL_AUTHENTICATION_PLUGIN: "mysql_native_password"
        options: >-
          --health-cmd="mysqladmin ping -u root"
          --health-interval=15s
          --health-timeout=5s
          --health-retries=6
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'
      - run: poetry install
      - name: Run Pytests
        run: poetry run pytest finbot_platform/tests/

